WifiCountryCode: "DE"
VideoAntiFlickerRate: 50
VideoQualityDefault: "high"
NotifyOnMotionAlert: true
NotifyOnMotionTimeoutAlert: false
NotifyOnAudioAlert: false
NotifyOnButtonPressAlert: true
MotionRecordingWebHookUrl: "https://hass.iflorian.com/api/webhook/CHANGE_ME"
DatabasePath: "/data/arlo.db"
Go2RTCEnabled: true
Go2RTCConfigPath: "/data/go2rtc.yaml"
Go2RTCApiUrl: "http://arlo-go2rtc:1984"
